# Attack: Clean Graph
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Prune' --defense_mode 'none' --device_id 0 > ./logs/Arxiv/Arxiv_Clean_Prune_gcn2gcn.log 2>&1 &
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Prune' --defense_mode 'prune' --prune_thr 0.3 --device_id 0 > ./logs/Arxiv/Arxiv_Clean_Prune_gcn2gcn.log 2>&1 &
## Defend: Isolated
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Prune' --defense_mode 'isolate' --prune_thr 0.3 --device_id 3 > ./logs/Arxiv/Arxiv_Clean_Isolate_gcn2gcn.log 2>&1 &

# Attack: Rand.Samp.
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Rand_Samp' --defense_mode 'none' --evaluate_mode 'overall' --device_id 2 > ./logs/Arxiv/Arxiv_Rand_Samp_Prune_gcn2gcn.log 2>&1 &
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Rand_Samp' --defense_mode 'prune' --prune_thr 0.3 --evaluate_mode 'overall' --device_id 2 > ./logs/Arxiv/Arxiv_Rand_Samp_Prune_gcn2gcn.log 2>&1 &
## Defend: Isolated
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Rand_Samp' --defense_mode 'isolate' --prune_thr 0.3 --evaluate_mode 'overall' --device_id 2 > ./logs/Arxiv/Arxiv_Rand_Samp_Isolate_gcn2gcn.log 2>&1 &

# Attack: Rand.Gene.
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Rand_Gene' --defense_mode 'none' --evaluate_mode 'overall' --device_id 0 > ./logs/Arxiv/Arxiv_Rand_Gene_Prune_gcn2gcn.log 2>&1 &
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Rand_Gene' --defense_mode 'prune' --prune_thr 0.3 --evaluate_mode 'overall' --device_id 0 > ./logs/Arxiv/Arxiv_Rand_Gene_Prune_gcn2gcn.log 2>&1 &
## Defend: Isolated
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Rand_Gene' --defense_mode 'isolate' --prune_thr 0.3 --evaluate_mode 'overall' --device_id 3 > ./logs/Arxiv/Arxiv_Rand_Gene_Isolate_gcn2gcn.log 2>&1 &

# Attack: GTA
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none' --device_id 0 > ./logs/Arxiv/Arxiv_Basic_Prune_gcn2gcn.log 2>&1 &
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune' --prune_thr 0.3 --device_id 3 > ./logs/Arxiv/Arxiv_Basic_Prune_gcn2gcn.log 2>&1 &
## Defend: Isolated
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate' --prune_thr 0.3 --device_id 0 > ./logs/Arxiv/Arxiv_Basic_Isolate_gcn2gcn.log 2>&1 &

# Attack: Ours
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none' --homo_loss_weight 3 --dis_weight 1 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn.log 2>&1 &
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune' --prune_thr 0.3 --homo_loss_weight 3 --dis_weight 1 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn.log 2>&1 &
## Defend: Isolated
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate' --prune_thr 0.3 --homo_loss_weight 3 --dis_weight 1 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn.log 2>&1 &

# Attack: Without Selection
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none' --homo_loss_weight 3 --dis_weight 1 --selection_method 'none' --device_id 2 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn.log 2>&1 &
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune' --prune_thr 0.3 --homo_loss_weight 3 --dis_weight 1 --selection_method 'none' --device_id 2 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn.log 2>&1 &
## Defend: Isolated
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate' --prune_thr 0.3 --homo_loss_weight 3 --dis_weight 1 --selection_method 'none' --device_id 2 > ./logs/Arxiv/Arxiv_Unno_Isolate_gcn2gcn.log 2>&1 &

# Attack: Without Constraint
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none' --homo_loss_weight 0 --dis_weight 1 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Sel_Prune_gcn2gcn.log 2>&1 &
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune' --prune_thr 0.3 --homo_loss_weight 0 --dis_weight 1 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Sel_Prune_gcn2gcn.log 2>&1 &
## Defend: Isolated
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --train_lr 0.02 --hidden 64 --vs_ratio 0.001 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate' --prune_thr 0.3 --homo_loss_weight 0 --dis_weight 1 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Sel_Isolate_gcn2gcn.log 2>&1 &

# Attack: Ours
## Defend: Prune
nohup python run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 1 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs160.log 2>&1 &

# Attack: Ours
## Defend: Prune
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 80 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs80.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs160.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 240 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs240.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs320.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs400.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1500 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs480_homo50_epoch1500.log 2>&1 &
## Defend: Prune
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 80 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs80.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs160.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 240 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs240.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs320.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs400.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1000 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs480_epoch1000.log 2>&1 &
## Defend: Isolate
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 80 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs80.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs160.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 240 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs240.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs320.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs400.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1000 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs480_epoch1000.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs480_homo200_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 300 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs480_homo300_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 400 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs480_homo400_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 400 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs320_homo200.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs160_homo200_epoch800.log 2>&1 &

nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 1 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs160_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs320_1.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs400_1.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 400 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 50 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs320_2.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 400 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 50 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs400_2.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1500 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 50 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_None_gcn2gcn_vs400_homo50_epoch1500.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 600 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 1 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs320_epoch600.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1500 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 1 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs320_epoch1500.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 600 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs400_1.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs320_1.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 400 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 50 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs400_1.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1000 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs320_epoch1000.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1000 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs400_epoch1000.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs320_homo200_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs400_homo200_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs160_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 240 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs240_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs320_homo200_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs400_homo200_epoch800_outr1024.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs480_homo200_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1500 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 1 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs480_homo200_epoch1500_out1024.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 80 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Prune_gcn2gcn_vs80_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 1500 --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 0 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs320_homo200_epoch1500.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 80 --prune_thr 0.8 --homo_loss_weight 200 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 2 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs80_homo200_epoch800.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --trojan_epochs 800 --use_vs_number --vs_number 480 --prune_thr 0.8 --homo_loss_weight 300 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'isolate'  --dis_weight 0 --selection_method 'cluster_degree' --device_id 3 > ./logs/Arxiv/Arxiv_Ours_Isolate_gcn2gcn_vs480_homo300_epoch800_out1024.log 2>&1 &
# Attack: Without Selection
## Defend: Prune
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 80 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'none' --device_id 2 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs80.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'none' --device_id 2 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs160.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 240 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'none' --device_id 3 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs240.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'none' --device_id 0 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs320.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --attack_method 'Basic' --defense_mode 'none'  --dis_weight 0 --selection_method 'none' --device_id 1 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs400.log 2>&1 &

## Defend: Prune
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 80 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --use_vs_number --vs_number 80 --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 1 --selection_method 'none' --device_id 0 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs80.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 160 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --use_vs_number --vs_number 160 --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 1 --selection_method 'none' --device_id 1 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs160.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 240 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --use_vs_number --vs_number 240 --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 1 --selection_method 'none' --device_id 2 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs240.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 320 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --use_vs_number --vs_number 320 --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 1 --selection_method 'none' --device_id 3 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs320.log 2>&1 &
nohup python -u run_adaptive.py --dataset 'ogbn-arxiv' --use_vs_number --vs_number 400 --prune_thr 0.8 --homo_loss_weight 100 --homo_boost_thrd 0.8 --model 'GCN' --test_model 'GCN' --use_vs_number --vs_number 400 --attack_method 'Basic' --defense_mode 'prune'  --dis_weight 1 --selection_method 'none' --device_id 3 > ./logs/Arxiv/Arxiv_Unno_Prune_gcn2gcn_vs400.log 2>&1 &
